name: Feature request
description: Suggest an improvement or a contribution idea.
title: "feat: "
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Problem to solve
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed approach
  - type: checkboxes
    attributes:
      label: Contribution
      options:
        - label: I would like to work on this.
